### ISSUE TITLE
Possible Copy/Refactor of your code

### ISSUE THREAD

**Issue by hYdos** [minad/chasm#2]
It seems that your project may be used without permission and without attribution here(as far as i know, I might be wrong):
https://github.com/QuiltMC/chasm
I may be wrong, but this was from a quick overview from a few people I know.

**Comment by minad** [comment]
I see. The license requires attribution. Also the license must be preserved.

**Comment by minad** [comment]
I looked briefly at the code and the project looks very different, also the initial commits. Do you have an indication that some code was used from here?

**Comment by gdude2002** [comment]
Apologies, this user appears to be on some kind of harassment campaign at the moment.

The two projects are not related.

**Comment by hYdos** [comment]
Odd how you follow the repo and know I did this 🤔
